global:
  scrape_interval: 5s 
  evaluation_interval: 5s

scrape_configs:
  # 1. Zyrabit Brain
  - job_name: 'zyrabit-api'
    metrics_path: '/metrics'
    scrape_timeout: 5s
    static_configs:
      - targets: ['api-rag:8080']
        labels:
          env: 'local-docker'
          service: 'rag-engine'

  # 2. Prometheus Server
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']