global:
  scrape_interval: 5s   

scrape_configs:
  - job_name: 'zyrabit-brain'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-rag:8080']

  - job_name: 'prometheus-self'
    static_configs:
      - targets: ['localhost:9090']